### ISSUE TITLE
Where did you do encode hidden status lfq quantization?

### ISSUE THREAD

**Issue by xesdiny** [bornfly-detachment/asymmetric_magvitv2#5]
I found that the entire code inference process does not use a quantizer to discretize the encoding representation, nor does it use `VectorQuantizerWithInputProjection` for conversion. It is directly handed over to the decoder original encode_z for the decoding process? This process still uses the pipeline + weight of SVD 3dvae.
Why use `DiagonalGaussianRegularizer` norm  encoder ouput?

**Comment by RenShuhuai-Andy** [comment]
same question

**Comment by bornfly-detachment** [comment]
> I found that the entire code inference process does not use a quantizer to discretize the encoding representation, nor does it use `VectorQuantizerWithInputProjection` for conversion. It is directly handed over to the decoder original encode_z for the decoding process? This process still uses the pipeline + weight of SVD 3dvae. Why use `DiagonalGaussianRegularizer` norm encoder ouput?

The model was trained only with a continuous VAE and did not include VQ training. It is designed specifically for video generation services and cannot be applied to LLMs. To adapt it for the videoPoet series, you would need to add a VectorQuantizer and fine-tune it.
